version: '3'

tasks:
  build:
    cmds:
      - docker compose build
  up:
    cmds:
      - docker compose up -d
  down:
    cmds:
      - docker compose down
  destroy:
    cmds:
      - docker compose down --volumes --rmi all --remove-orphans
  launch:
    cmds:
      - docker compose exec stream-extractor functions_framework --target=function
  bash:
    cmds:
      - docker compose exec stream-extractor bash
